### PR TITLE
LAPS CLI: optional use of machine account for LDAP authentication

### PR DESCRIPTION
**Pull request by michaelbarkdoll**

### CODE REVIEW

**Comment by schorschii** [comment]
What does this change do?

**Comment by michaelbarkdoll** [comment]
Just allows laps-cli.py to initializing kerberos if the ticket is expired
from a cronjib, etc..  basically, cut and paste your code from
laps-runner.py with a few extra lines for the logic.

Hope it helps, it solved an issue for me so that I can use laps-cli.py to
output the expiration date for reporting to a zabbix server trigger.

**Comment by schorschii** [comment]
Sorry for the delay. I just got back to this project and I think I understand the intention of this PR now.

You use the machine account for LDAP authentication within the LAPS client (instead of regular user authentication, which can also be done via Kerberos, that's why my initial confusion). This is not the original idea but may be helpful in some situations. Limitations are:
- the client must be started with root permissions in order to read `/etc/krb5.keytab`
- the machine account has no read access to its admin password (only write access), so it can only be used for other values like the expiration date

In order to merge this, this behavior should not be default. I would prefer a command line switch (e.g. --use-machine-account) to enable this feature for such monitoring use cases you described.

**Comment by schorschii** [comment]
Closed due to inactivity. Feel free to reopen if there are any updates on this.

**Pull request closed without merging**
