### PR TITLE
Update laps-cli.py

### PR DESCRIPTION
**Pull request by michaelbarkdoll**
Enforce ssl unless --no-ssl
Allow for set-password with -p <password>

### CODE REVIEW

**Comment by schorschii** [comment]
SSL can already be enforced via config file. Therefore, the command line parameter is redundant.

Which use case do you have for changing the password in the LDAP directory with the client? This action does not change the admin password on the target machine. If you do this, the correct admin password for the target machine is lost. Maybe what you are looking for is laps-runner.py?

**Comment by michaelbarkdoll** [comment]
Thanks, does laps-runner.py allow for stdin of the AD authentication and password?  I need to reset the password periodically every x number of days and this particular script wouldn't work with kerberos via an sssd joined linux rhel 8.5 machine, so I'm doing to process manually via ansible playbooks.

**Comment by schorschii** [comment]
No, laps-runner.py does not use username and password; it authenticates against the AD using the computer account (with it's secret stored in `/etc/krb5.keytab`).

Why does the script not work via an SSSD joined Linux RHEL 8.5 machine? We should make it work instead of creating a workaround.

I still don't understand the use case. If you only change the password in AD, the correct admin password for this computer is lost. If you (periodically) need to force a new admin password, **you should set the expiry date** to something in the past (which laps-gui.py and laps-cli.py already can). The laps-runner.py (and also the original LAPS from Microsoft on Windows machines) will notice this on the next run and creates a new random password, will set it for the local administrator and writes it into the AD.

**Comment by michaelbarkdoll** [comment]
Thanks, yes this can probably be closed in that case.  However, do you mind if I ask why the following is not working with an RHEL 8 machine joined via SSSD.

```
$ ./laps-runner.py -c /root/LAPS4LINUX/LAPS4LINUX/laps-runner.json
LAPS4LINUX Runner v1.5.2
If you like LAPS4LINUX please consider making a donation to support further development (https://github.com/schorschii/laps4linux).

Traceback (most recent call last):
  File "./laps-runner.py", line 222, in main
    runner.initKerberos()
  File "./laps-runner.py", line 86, in initKerberos
    if res.returncode != 0: raise Exception(' '.join(cmd)+' returned non-zero exit code '+str(res.returncode))
Exception: kinit -k -c /tmp/laps.temp CS-123456$ returned non-zero exit code 1
$ 
kinit -k -c /tmp/laps.temp CS-123456$ 
kinit: Keytab contains no suitable keys for CS-123456$@domain.college.edu while getting initial credentials
$
$ cat laps-runner.json 
{
    "server": [
        {
            "address": "domain.college.edu",
            "port": 636,
            "ssl": true
        }
    ],
    "domain": "domain.college.edu",
    "cred-cache-file": "/tmp/laps.temp",
    "client-keytab-file": "/etc/krb5.keytab",
    "ldap-attribute-password": "ms-Mcs-AdmPwd",
    "ldap-attribute-password-expiry": "ms-Mcs-AdmPwdExpirationTime",
    "hostname": "CS-123456",
    "password-change-user": "root",
    "password-days-valid": 30,
    "password-length": 15,
    "password-alphabet": "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
}
$ klist -c /tmp/laps.temp
Ticket cache: FILE:/tmp/laps.temp
Default principal: CS-537998$@domain.college.edu

Valid starting       Expires              Service principal
05/26/2022 09:40:14  05/26/2022 19:40:14  krbtgt/domain.college.edu@domain.college.edu
	renew until 05/27/2022 09:40:14
$
```

**Comment by michaelbarkdoll** [comment]
Thanks, yes this can be closed in that case.  Do you mind if I ask why I'm seeing the following error on RHEL 8 joined with adcli via SSSD. 

"gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server not found in Kerberos database"

```
[root@CS-123456 LAPS4LINUX]# ./laps-runner.py -c /root/LAPS4LINUX/LAPS4LINUX/laps-runner.json
LAPS4LINUX Runner v1.5.2
If you like LAPS4LINUX please consider making a donation to support further development (https://github.com/schorschii/laps4linux).

Traceback (most recent call last):
  File "./laps-runner.py", line 223, in main
    runner.connectToServer()
  File "./laps-runner.py", line 105, in connectToServer
    self.connection = ldap3.Connection(self.server, authentication=ldap3.SASL, sasl_mechanism=ldap3.KERBEROS, auto_bind=True)
  File "/usr/lib/python3.6/site-packages/ldap3/core/connection.py", line 356, in __init__
    self._do_auto_bind()
  File "/usr/lib/python3.6/site-packages/ldap3/core/connection.py", line 382, in _do_auto_bind
    self.bind(read_server_info=True)
  File "/usr/lib/python3.6/site-packages/ldap3/core/connection.py", line 608, in bind
    response = self.do_sasl_bind(controls)
  File "/usr/lib/python3.6/site-packages/ldap3/core/connection.py", line 1336, in do_sasl_bind
    result = sasl_gssapi(self, controls)
  File "/usr/lib/python3.6/site-packages/ldap3/protocol/sasl/kerberos.py", line 118, in sasl_gssapi
    out_token = ctx.step(in_token)
  File "<decorator-gen-15>", line 2, in step
  File "/usr/lib64/python3.6/site-packages/gssapi/_utils.py", line 167, in check_last_err
    return func(self, *args, **kwargs)
  File "<decorator-gen-5>", line 2, in step
  File "/usr/lib64/python3.6/site-packages/gssapi/_utils.py", line 127, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/gssapi/sec_contexts.py", line 521, in step
    return self._initiator_step(token=token)
  File "/usr/lib64/python3.6/site-packages/gssapi/sec_contexts.py", line 542, in _initiator_step
    token)
  File "gssapi/raw/sec_contexts.pyx", line 244, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server not found in Kerberos database

[root@CS-123456 LAPS4LINUX]# klist -c /tmp/laps.temp
Ticket cache: FILE:/tmp/laps.temp
Default principal: CS-123456$@DOMAIN.COLLEGE.EDU

Valid starting       Expires              Service principal
05/26/2022 10:46:17  05/26/2022 20:46:17  krbtgt/DOMAIN.COLLEGE.EDU@DOMAIN.COLLEGE.EDU
	renew until 05/27/2022 10:46:17
[root@CS-123456 LAPS4LINUX]# kinit -k -c /tmp/laps.temp CS-123456$
[root@CS-123456 LAPS4LINUX]# echo $?
0
[root@CS-123456 LAPS4LINUX]# klist -c /tmp/laps.temp
Ticket cache: FILE:/tmp/laps.temp
Default principal: CS-123456$@DOMAIN.COLLEGE.EDU

Valid starting       Expires              Service principal
05/26/2022 10:47:39  05/26/2022 20:47:39  krbtgt/DOMAIN.COLLEGE.EDU@DOMAIN.COLLEGE.EDU
	renew until 05/27/2022 10:47:39
[root@CS-123456 LAPS4LINUX]# 
[root@CS-123456 LAPS4LINUX]# cat /root/LAPS4LINUX/LAPS4LINUX/laps-runner.json
{
    "server": [
        {
            "address": "domain.college.edu",
            "port": 636,
            "ssl": true
        }
    ],
    "domain": "domain.college.edu",
    "cred-cache-file": "/tmp/laps.temp",
    "client-keytab-file": "/etc/krb5.keytab",
    "ldap-attribute-password": "ms-Mcs-AdmPwd",
    "ldap-attribute-password-expiry": "ms-Mcs-AdmPwdExpirationTime",
    "hostname": "CS-123456",
    "password-change-user": "root",
    "password-days-valid": 30,
    "password-length": 15,
    "password-alphabet": "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
}
[root@CS-123456 LAPS4LINUX]# 
```

**Comment by michaelbarkdoll** [comment]
I'm wondering if I'm seeing:

"gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure. Minor code may provide more information, Minor (2529638919): Server not found in Kerberos database" 

Due to there being no reverse dns entry inside AD for my machine that is joined to AD.  I have the following inside /etc/krb5.conf to avoid this:

```
[libdefaults]
        rdns = false
```

**Comment by michaelbarkdoll** [comment]
I had our AD administrators update the reverse dns record for the machine inside AD to eliminate DNS being the issue.  However, I'm still getting the same error.

**Comment by schorschii** [comment]
> Thanks, yes this can be closed in that case. Do you mind if I ask why I'm seeing the following error on RHEL 8 joined with adcli via SSSD.

Thanks for your response. So I'm closing this PR but I'll still help you out with the error "Server not found in Kerberos database".

Can you please post the output of the following commands? Please replace `<COMPUTERNAME>` with your hostname but do not forget the trailing dollar sign.
```
sudo kinit -k -c /tmp/laps.temp <COMPUTERNAME>$
sudo klist -c /tmp/laps.temp
```

**Comment by michaelbarkdoll** [comment]
```
Please try to set the FQDN of the Kerberos server in laps-runner.json (not only the domain name):

"server": [
        {
            "address": "dc1.domain.college.edu",
            "port": 636,
            "ssl": true
        }
    ],
```

> Thanks for the reply, same error:
```
./laps-runner.py -c /root/LAPS4LINUX/LAPS4LINUX/laps-runner.json
LAPS4LINUX Runner v1.5.2
If you like LAPS4LINUX please consider making a donation to support further development (https://github.com/schorschii/laps4linux).

Traceback (most recent call last):
  File "./laps-runner.py", line 254, in main
    runner.connectToServer()
  File "./laps-runner.py", line 116, in connectToServer
    self.connection = ldap3.Connection(self.server, sasl_credentials=(ReverseDnsSetting.OPTIONAL_RESOLVE_ALL_ADDRESSES,), authentication=ldap3.SASL, sasl_mechanism=ldap3.KERBEROS, auto_bind=True)
  File "/usr/local/lib/python3.6/site-packages/ldap3/core/connection.py", line 363, in __init__
    self._do_auto_bind()
  File "/usr/local/lib/python3.6/site-packages/ldap3/core/connection.py", line 389, in _do_auto_bind
    self.bind(read_server_info=True)
  File "/usr/local/lib/python3.6/site-packages/ldap3/core/connection.py", line 615, in bind
    response = self.do_sasl_bind(controls)
  File "/usr/local/lib/python3.6/site-packages/ldap3/core/connection.py", line 1343, in do_sasl_bind
    result = sasl_gssapi(self, controls)
  File "/usr/local/lib/python3.6/site-packages/ldap3/protocol/sasl/kerberos.py", line 109, in sasl_gssapi
    return _posix_sasl_gssapi(connection, controls)
  File "/usr/local/lib/python3.6/site-packages/ldap3/protocol/sasl/kerberos.py", line 232, in _posix_sasl_gssapi
    out_token = ctx.step(in_token)
  File "<decorator-gen-15>", line 2, in step
  File "/usr/lib64/python3.6/site-packages/gssapi/_utils.py", line 167, in check_last_err
    return func(self, *args, **kwargs)
  File "<decorator-gen-5>", line 2, in step
  File "/usr/lib64/python3.6/site-packages/gssapi/_utils.py", line 127, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/gssapi/sec_contexts.py", line 521, in step
    return self._initiator_step(token=token)
  File "/usr/lib64/python3.6/site-packages/gssapi/sec_contexts.py", line 542, in _initiator_step
    token)
  File "gssapi/raw/sec_contexts.pyx", line 244, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server not found in Kerberos database

```

**Comment by michaelbarkdoll** [comment]
I noticed the DC1.DOMAIN.COLLEGE.EDU has an improper rdns entry.  I'm getting that updated now to see if that resolves this issue.

**Comment by michaelbarkdoll** [comment]
Thanks to your assistance this issue is now resolved.  

Just an update for anyone else experiencing this issue.  We had one server that had a proper domain name and reverse dns entry, but that server was not in the Kerberos database.  

The following command showed me what servers were in the Kerberos database and after I had those server rdns entries corrected the laps-runney.py script started working.
```
nslookup -query=srv _kerberos._udp.DOMAIN.COLLEGE.EDU
```

Really appreciate your hard work on this script and sharing it with the community!!!

**Comment by schorschii** [comment]
Thanks for your feedback! :)

**Pull request closed without merging**
